### PR TITLE
Update subscription_management_system_db_1.0.sql

### PR DESCRIPTION
**Pull request by w280749941**

### CODE REVIEW

**Review by xiao-peng1006 — COMMENTED** [review]
1, service_provider_id will conflict with another foreign key constraint
2, subscriptions under the same service provider may have different subscription plans to choose

**Comment by w280749941** [comment]
> 1, service_provider_id will conflict with another foreign key constraint
1. Can you provide an example? I don't think it will conflict with anything.

> 2, subscriptions under the same service provider may have different subscription plans to choose


2. Yes, your statement is correct.


3. After the change, the user can query the table to figure out how many plans a service provider owns.

**Review by xiao-peng1006 — COMMENTED** [review]
An error occurred when processing the query: "Error Code: 1826. Duplicate foreign key constraint name 'service_provider_id'".

**Comment by w280749941** [comment]
Issue fixed. Try again.

**Review by xiao-peng1006 — APPROVED** [review]
Reviewed and approved

**Pull request merged**
